package hotelbooking;

public class Form_Admin extends javax.swing.JFrame {

    /**
     * Creates new form From_Admin
     */
    public Form_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnQuanLyUser = new javax.swing.JButton();
        btnQuanLyPhong = new javax.swing.JButton();
        btnQuanLyDichVu = new javax.swing.JButton();
        btnQuanLyDatPhong = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPhanQuyenHeThong = new javax.swing.JButton();
        btnPhanQuyenHeThong1 = new javax.swing.JButton();
        btnContact = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCheckSession = new javax.swing.JButton();
        btnSGA = new javax.swing.JButton();
        btnInstance = new javax.swing.JButton();
        btnPGA = new javax.swing.JButton();
        btnDataFile = new javax.swing.JButton();
        btnControlFile = new javax.swing.JButton();
        btnSPFile = new javax.swing.JButton();
        btnQLProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnQuanLyUser.setBackground(new java.awt.Color(0, 153, 153));
        btnQuanLyUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuanLyUser.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/2.png"))); // NOI18N
        btnQuanLyUser.setText("Quản lý User");
        btnQuanLyUser.setBorderPainted(false);
        btnQuanLyUser.setDefaultCapable(false);
        btnQuanLyUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyUserActionPerformed(evt);
            }
        });

        btnQuanLyPhong.setBackground(new java.awt.Color(0, 153, 153));
        btnQuanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuanLyPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/6.png"))); // NOI18N
        btnQuanLyPhong.setText("Quản lý Phòng");
        btnQuanLyPhong.setBorderPainted(false);
        btnQuanLyPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyPhong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyPhongActionPerformed(evt);
            }
        });

        btnQuanLyDichVu.setBackground(new java.awt.Color(0, 153, 153));
        btnQuanLyDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuanLyDichVu.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/4.png"))); // NOI18N
        btnQuanLyDichVu.setText("Quản lý Dịch Vụ");
        btnQuanLyDichVu.setBorderPainted(false);
        btnQuanLyDichVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDichVuActionPerformed(evt);
            }
        });

        btnQuanLyDatPhong.setBackground(new java.awt.Color(0, 153, 153));
        btnQuanLyDatPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuanLyDatPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/3.png"))); // NOI18N
        btnQuanLyDatPhong.setText("Quản Lý Lịch Sử Đặt Phòng");
        btnQuanLyDatPhong.setBorderPainted(false);
        btnQuanLyDatPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyDatPhong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQuanLyDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDatPhongActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Đăng xuất");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome Admin");

        btnPhanQuyenHeThong.setBackground(new java.awt.Color(0, 153, 153));
        btnPhanQuyenHeThong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPhanQuyenHeThong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhanQuyenHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/6.png"))); // NOI18N
        btnPhanQuyenHeThong.setText("Phân Quyền Hệ Thống");
        btnPhanQuyenHeThong.setBorderPainted(false);
        btnPhanQuyenHeThong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhanQuyenHeThong.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPhanQuyenHeThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanQuyenHeThongActionPerformed(evt);
            }
        });

        btnPhanQuyenHeThong1.setBackground(new java.awt.Color(0, 153, 153));
        btnPhanQuyenHeThong1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPhanQuyenHeThong1.setForeground(new java.awt.Color(255, 255, 255));
        btnPhanQuyenHeThong1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/6.png"))); // NOI18N
        btnPhanQuyenHeThong1.setText("Phân Quyền Người Dùng");
        btnPhanQuyenHeThong1.setBorderPainted(false);
        btnPhanQuyenHeThong1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhanQuyenHeThong1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPhanQuyenHeThong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanQuyenHeThong1ActionPerformed(evt);
            }
        });

        btnContact.setBackground(new java.awt.Color(0, 153, 153));
        btnContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContact.setForeground(new java.awt.Color(255, 255, 255));
        btnContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/2.png"))); // NOI18N
        btnContact.setText("Quản lý trò chuyện");
        btnContact.setBorderPainted(false);
        btnContact.setDefaultCapable(false);
        btnContact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnContact.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuanLyUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQuanLyPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQuanLyDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnPhanQuyenHeThong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQuanLyDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhanQuyenHeThong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(btnQuanLyUser)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyPhong)
                .addGap(12, 12, 12)
                .addComponent(btnQuanLyDichVu)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyDatPhong)
                .addGap(18, 18, 18)
                .addComponent(btnPhanQuyenHeThong)
                .addGap(18, 18, 18)
                .addComponent(btnPhanQuyenHeThong1)
                .addGap(18, 18, 18)
                .addComponent(btnContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9))
        );

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("hotelbooking");

        btnCheckSession.setText("Kiểm Tra Có Bao Nhiêu Sessions Đang Chạy");
        btnCheckSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckSessionActionPerformed(evt);
            }
        });

        btnSGA.setText("Kiểm Tra SGA");
        btnSGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSGAActionPerformed(evt);
            }
        });

        btnInstance.setText("Kiểm Tra Instance");
        btnInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstanceActionPerformed(evt);
            }
        });

        btnPGA.setText("Kiểm Tra PGA");
        btnPGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPGAActionPerformed(evt);
            }
        });

        btnDataFile.setText("Kiểm Tra DataFile");
        btnDataFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataFileActionPerformed(evt);
            }
        });

        btnControlFile.setText("Kiểm tra ControlFile");
        btnControlFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlFileActionPerformed(evt);
            }
        });

        btnSPFile.setText("Kiểm Tra SPFile");
        btnSPFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPFileActionPerformed(evt);
            }
        });

        btnQLProfile.setText("Quản lý Profile");
        btnQLProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSGA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInstance, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                            .addComponent(btnPGA, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckSession))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSPFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDataFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnControlFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPGA)
                    .addComponent(btnDataFile))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSGA)
                    .addComponent(btnControlFile))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstance)
                    .addComponent(btnSPFile))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckSession)
                    .addComponent(btnQLProfile))
                .addContainerGap(199, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyUserActionPerformed
        Form_ManageUser form = new Form_ManageUser();
        form.show();
    }//GEN-LAST:event_btnQuanLyUserActionPerformed

    private void btnQuanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyPhongActionPerformed
        Form_ManageRoom form = new Form_ManageRoom();
        form.show();
        
    }//GEN-LAST:event_btnQuanLyPhongActionPerformed

    private void btnQuanLyDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDichVuActionPerformed
        Form_ManageService form = new Form_ManageService();
        form.show();
        
    }//GEN-LAST:event_btnQuanLyDichVuActionPerformed

    private void btnQuanLyDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDatPhongActionPerformed
        Form_ManageBooking form = new Form_ManageBooking();
        form.show();
        
    }//GEN-LAST:event_btnQuanLyDatPhongActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnCheckSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckSessionActionPerformed
        hotelbooking.Class_SessionInfo.main(null);
    }//GEN-LAST:event_btnCheckSessionActionPerformed

    private void btnSGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSGAActionPerformed
        hotelbooking.Class_SGA.main(null);
    }//GEN-LAST:event_btnSGAActionPerformed

    private void btnInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstanceActionPerformed
        hotelbooking.Class_Instance.main(null);
    }//GEN-LAST:event_btnInstanceActionPerformed

    private void btnPGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPGAActionPerformed
        hotelbooking.Class_PGA.main(null);
    }//GEN-LAST:event_btnPGAActionPerformed

    private void btnDataFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataFileActionPerformed
        hotelbooking.Class_DataFile.main(null);
    }//GEN-LAST:event_btnDataFileActionPerformed

    private void btnSPFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPFileActionPerformed
        hotelbooking.Class_SPFile.main(null);
    }//GEN-LAST:event_btnSPFileActionPerformed

    private void btnControlFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlFileActionPerformed
        hotelbooking.Class_ControlFile.main(null);
    }//GEN-LAST:event_btnControlFileActionPerformed

    private void btnQLProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLProfileActionPerformed
        Form_ProfileForAdmin form = new Form_ProfileForAdmin();
        form.show();
    }//GEN-LAST:event_btnQLProfileActionPerformed

    private void btnPhanQuyenHeThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanQuyenHeThongActionPerformed
        Form_GrantSystemPrivileges form = new Form_GrantSystemPrivileges();
        form.show();
    }//GEN-LAST:event_btnPhanQuyenHeThongActionPerformed

    private void btnPhanQuyenHeThong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanQuyenHeThong1ActionPerformed
        Form_GrantObjectPrivilege form = new Form_GrantObjectPrivilege();
        form.show();
    }//GEN-LAST:event_btnPhanQuyenHeThong1ActionPerformed

    private void btnContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactActionPerformed
        Form_ManagerChatter form = new Form_ManagerChatter();
        form.show();
    }//GEN-LAST:event_btnContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckSession;
    private javax.swing.JButton btnContact;
    private javax.swing.JButton btnControlFile;
    private javax.swing.JButton btnDataFile;
    private javax.swing.JButton btnInstance;
    private javax.swing.JButton btnPGA;
    private javax.swing.JButton btnPhanQuyenHeThong;
    private javax.swing.JButton btnPhanQuyenHeThong1;
    private javax.swing.JButton btnQLProfile;
    private javax.swing.JButton btnQuanLyDatPhong;
    private javax.swing.JButton btnQuanLyDichVu;
    private javax.swing.JButton btnQuanLyPhong;
    private javax.swing.JButton btnQuanLyUser;
    private javax.swing.JButton btnSGA;
    private javax.swing.JButton btnSPFile;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
